#+title: Lista de exercícios 3 - shell
#+author: Pedro Leal

* 1 - Com suas palavras, explique o que é um shell
Shell é um programa, uma interface, renderizada através de uma CLI ou GUI e que interpreta e executa comandos que interagem com ferramentas e funções do sistema operacional. 

* 2 - Quero executar esta sequência de comandos: ~cat xx.txt, ls, sort~ e guardar num arquivo ~.txt~. Cite ao menos uma forma de fazer isso, de maneira que o arquivo final tenha o conteúdo do ~ls~ e do ~cat~, não importando a ordem dos comandos.
cat teste.txt > result.txt && ls >> result.txt && sort result.txt > sorted.txt 

Também seria possível executar os comandos criando um script e utilizando a técnica shebang.

* 3 - Qual a utilidade de usar a técnica de ~shebang~?
Com a técnica shebang podemos especificar qual programa utilizar para executar um arquivo e executá-lo contendo todos os comandos que desejamos ao invés de executar um comando de cada vez ou em sequência utilizando um operador lógico. 

* 4 - Abaixo, serão listadas várias ações. Execute uma por vez no terminal e escreva o comando que usou logo em seguida.
- Estrutura de diretórios sugerida
#+begin_src bash
./ccuenf
./exercicios
#+end_src

| ação                                                                                                          | comando |
|---------------------------------------------------------------------------------------------------------------+---------|
| Verifique em qual diretório você está                                                                         |    pwd    |
| Crie a estrutura de diretórios sugerida logo acima na ~home~ do usuário                                         |    mkdir ccuenf ; mkdir exercicios     |
| Crie um arquivo "numeros.txt" com o ~cat~, não importa a quantidade de números                                  |    cat > numeros.txt     |
| Duplique "numeros.txt" para "numeros1.txt" e "numeros2.txt"                                                   |    cat numeros.txt > numeros1.txt ; cat numeros.txt > numeros2.txt     |
| Copie todos os arquivos com extensão ~.txt~ para a pasta "exercicios"                                           |    cp *.txt /home/exercicios     |
| Exiba os arquivos da pasta "exercicios" com seus detalhes (permissões, tamanho e etc) sem sair da pasta atual |     ls -l /home/exercicios   |
| Apague a pasta "ccuenf" e "exercicios"                                                                        |     rm -r ccuenf exercicios    |
* 5 - Liste todos os arquivos da pasta /bin, inverta a ordem (de Z para A) e depois salve num arquivo. Quais foram os comandos utilizados? Não é obrigatório executar a sequência em apenas uma linha.
ls /bin > result.txt 
sort -r result.txt > sorted.txt 

* 6 - Crie um arquivo ~.txt~ com o centeúdo da execução de ~man <comando>~ - onde "comando" é qualquer comando linux conhecido e que possua um manual - e inverta a ordem das linhas, procure pela palavra "the" e conte o número de ocorrências. Coloque aqui seu resultado e qual comando usou para pegar o manual.
man ls > lsManual.txt
tac lsManual.txt > inverseManual.txt
grep -o -i -w "the" inverseManual.txt | wc -w

Ocorrências: 21

* 7 - Escolha um ou mais programas da lista e tente instalá-lo, execute-o e descreva o resultado.
| programas |
|-----------|
| sl        |
| cmatrix   |
| rig       |
| nyancat   |

Programa instalado: sl 

Descrição da execução: Exibiu uma animação de uma locomotiva em movimento. 

- Após terminar o exercício, remova o programa
* 8 - Qual o resultado das seguintes expressões?
- Já que as colunas da tabela são formadas por ~|~, não posso escrever o pipe dentro da tabela.
  Tem como escapar com o ~\vert~, porém ele só é renderizado no ~org-mode~ do ~emacs~ :/
- ~\vert~ == ~|~

| expressão                     | resultado |
|-------------------------------+-----------|
| =false && echo foo \vert\vert echo bar= |     bar      |
| =true && echo foo \vert\vert echo bar=  |     foo      |
| =true \vert\vert echo foo && echo bar=  |     bar     |
| =false \vert\vert echo foo && echo bar= |     foo bar     |