#+title: Lista de exercícios 2 - Linux
#+author: <colocar seu nome>

* 1 - Explique a definição de "Linux"
* 2 - Dado os diretórios da primeira tabela, correlacione-os com suas funções na segunda tabela:

| opção | diretório |
|-------+-----------|
| a     | ~/dev~      |
| b     | ~/etc~      |
| c     | ~/usr~      |
| d     | ~/opt~      |

| opção | função                                                                                               |
|-------+------------------------------------------------------------------------------------------------------|
|       | Localização de arquivos, programas e bibliotecas do escopo de usário ficam; não são dados essenciais |
|       | Diretório destino das mapeações de cada hardware                                                     |
|       | Aqui são encontrados softwares adicionais e proprietários                                            |
|       | Local onde as configurações do sistema ficam disponíveis de forma global                             |

* 3 - Escolha 3 (três) diretórios Linux a partir da raiz (~/~) e explique sua respectiva função.
Regras:
- Não vale repetir os diretórios da questão anterior ☺
* 4 - Qual a finalidade de existirem grupos em sistemas operacionais baseados no Linux?
* 5 - Descreva cada permissão:
- Exemplo:
=.rw-rw-rw-= -> ~.~ significa xxx, yyy tem permissões de nnn e mmm, etc...

| permissão  | descrição |
|------------+-----------|
| =.rw-rw-rw-= |           |
| =lr-x---rwx= |           |
| =drwxr-xr-x= |           |
| =.rw-r--r--= |           |
| =drwxrwxrwx= |           |

* 6 - Defina ~STDIN~, ~STDOUT~ e ~STDERR~
* 7 - Diferencie uma ~CLI~ de uma ~GUI~, apontando suas vantagens e desvantagens





1. Linux é o núcleo de alguns sistemas operacionais, chamado "kernel". Consiste em um conjunto de instruções que controla como será usado o processador, a memória, o disco e dispositivos periféricos. É o software presente em todo sistema operacional que diz como o computador deve funcionar.

2. 
| opção | função                                                                                               |
|-------+------------------------------------------------------------------------------------------------------|
|   c   | Localização de arquivos, programas e bibliotecas do escopo de usário ficam; não são dados essenciais |
|   a   | Diretório destino das mapeações de cada hardware                                                     |
|   d   | Aqui são encontrados softwares adicionais e proprietários                                            |
|   b   | Local onde as configurações do sistema ficam disponíveis de forma global                             |

3.
/boot - Contém os arquivos necessários para o boot, arquivos de configuração do boot e kernels;
/var - Contém arquivos variáveis, como logs e bancos de dados;
/tmp - Contém arquivos temporários.

4. Os grupos são essenciais para quando vários usuários utilizam o sistema (em rede) e alguns deles precisam de acesso a um mesmo arquivo ou grupo de arquivos, então esses usuários podem fazer parte de um mesmo grupo, facilitando assim o trabalho do administrador da rede.

5. 
| permissão  | descrição |
|------------+-----------|
| =.rw-rw-rw-= | Proprietário, grupo e outros têm permissão a leitura e escrita |
| =lr-x---rwx= | l significa que é um link simbólico, proprietário tem permissão de leitura e execução, grupo não tem nenhuma permissão e outros tem permissão a escrita, leitura e execução |
| =drwxr-xr-x= | d significa que é um diretório, proprietário tem permissão de leitura, escrita e execução, grupo e outros têm permissão a leitura e execução |
| =.rw-r--r--= | Proprietário tem permissão de leitura e escrita, grupo e outros têm permissão de apenas leitura |
| =drwxrwxrwx= | É um diretório. Proprietário, grupo e outros, todos têm todas as permissões |

6. 	STDIN - Significa "standard input", ou "entrada padrão". É o fluxo padrão de entrada de dados. A maioria dos comandos aceita sua entrada de STDIN; 
	SDOUT - Significa "standard output", ou "saída padrão". É o fluxo padrão de saída de dados. Os comandos gravam sua saída em STDOUT;
	STDERR - Significa "standard error", ou "erro padrão". É um fluxo padrão de saída, assim como o STDOUT, porém é apenas para mensagens de erros.

7. 
CLI - É a interface de linha de comandos.
	Vantagens: Há um leque muito maior de funcionalidades avançadas; Com a prática, linha de comandos é muito mais rápido de se realizar qualquer tarefa; Utiliza menos recursos do computador; Há a possibilidade de se fazer scripts para automatizar tarefas, etc; Há muito mais suporte para acesso remoto.
	Desvantagens: Mais difícil de ser utilizado por ter que gravar os comandos; Não é tão interessante para o uso de multitarefas.

GUI - É a interface gráfica do usuário.
	Vantagens: Muito mais fácil de ser utilizado; Melhor para multitarefas.
	Desvantagens: Usuários avançados precisam recorrer a CLI para algumas tarefas mais complexas; Utiliza mais recursos do computador; Não há a possibilidade de se criar scripts para automatizar tarefas.