#+title: Como nunca mais perder aquele arquivo/projeto?
#+author: Matheus de Souza Pessanha
#+email: 00119110328@pq.uenf.br

* Git
~git~ é uma ferramenta de DVCS (Distributed Version Control System), ou "sistema de controle de versões distribuido",
utilizado para versionar (criar versões) diferentes de um arquivo/projeto.

- Criado por Linus Torvalds
- Não é o único VCS, existem outros como: Subversion e Mercurial
- Almeja oferecer a maior flexibilidade, segurança e desempenho
- Relativamente difícil de aprender, pela quantidade de novos conceitos e comandos

** Diferença entre git e Github
- O ~git~ é de fato o software de VCS
- Github é uma plataforma de hospedagem de código fonte, que utiliza o ~git~
  - Outros exemplos, são:
    1. Gitlab
    2. BitBucket

** Instalando o git
- Existe uma versão oficial para windows: https://git-scm.com/download/win
  - Instala em conjunto o "git bash", um emulador de terminal bem limitado com o bash
- Em distros Linux baseadas no Debian, rode: =sudo apt install git=
  - Geralmente o ~git~ já vem instalado por padrão nas distros

** Conceitos iniciais
*** Repositório
Bem, nas outras aulas houve uma breve explição do que são repositórios! O ~git~ usa o mesmo conceito.

**** Repositório local
- Lugar onde fica os arquivos na sua máquina, de forma "local"
**** Repositório remoto
- Lugar para onde enviamos as mudanças locais e armazenamos todas as mudanças
- Geralmente usamos uma plataforma, como Github

*** Working tree
- "Árvore de trabalho", ou seja, local onde ficam as mudanças não commitadas
*** Commit
- Cria um ponto ("save") no seu repositório
- Responsável por criar a "linha do tempo" do projeto

*** Branch
- Imagine seu projeto como uma árvore
- Cria um novo "ramo" do seu projeto!
- Todo projeto possui uma branch raiz padrão ~master~ ou ~main~

*** Staging
- Passo anterior ao ~commit~
- Armazena as mudanças de forma temporária e facilmente reversível

*** Clonar
- É possível clonar repositórios remotos, ou seja, trazer o repositório remoto para sua máquina

*** Push
- Faz o upload dos commits locais para um repositório remoto

*** Pull
- Faz o download das mudanças de um repositório remoto para um local

*** HEAD
- Significa uma referência para o último commit e branch atual
*** Merge
- "Mesclar"
- Junta commits de uma branch em outra
- Não altera o histórico de commits
- Cria um novo commit para a confirmação da mesclagem
*** Rebase
- Reescreve todo o histórico de commits
- Não cria novos commits, apenas copia eles de uma branch e os coloca em outra,
  parecendo que a segunda branch nunca foi criada
- Possui uma versão interativa na qual é possível trocar as mensagens de commits e realizar outras modificações
  antes de juntar os commits
** Comandos
Antes de inciar os comandos, devemos configurar o git localmente, nos identificando:
#+begin_src bash

git config --global user.email "seu@email.com"
git config --global user.name "Seu nome"

#+end_src


*** git init
- Cria um reposit local no diretório atual
*** git clone <url-repo-remoto> [destino]
- Clona um repositório remoto para sua máquina
  - Existem duas formas de clonar um repositório:
    1. SSH
    2. HTTPS
*** git add <arquivos>
- Adiciona um ou mais arquivos para o staging
- =git add .= -> adiciona todo o diretório atual para staging
*** git status
- Mostra o estado atual do seu repositório local
*** git log
- Mostra o histórico dos commits
- =git log --graph= -> cria um "gráfico" com o histórico de commits
*** git commit -m <mensagem>
- Cria um commit com os arquivos em staging com uma mensagem
*** git push <repo-remoto> <branch-fonte>
- Faz o upload dos commits da "branch-fonte" para um repositório remoto
  - Geralmente chamamos o repositório remoto de "origin"
- =git push <repo-remoto> --delete <branch>= -> deleta uma branch remota
- =git push <repo-remoto> :<branch-antiga> <nova-branch>= -> renomeia uma branch remota
*** git remote
- =git remote -v= -> mostra todos os repositórios remotos
- =git remote add <nome> <url>= -> adiciona um novo remositório remoto localmente
- =git remote remove <nome>= -> remove um repositório remoto localmente
*** git fetch <repo-remoto>
- Sincroniza o repositório local e repositório remoto
*** git checkout
- =git checkout -b <nome-branch>= -> cria uma nova branch com o nome especificado e muda o ~HEAD~ para ela
- =git checkout <branch>= -> muda a ~HEAD~ para uma branch existente
*** git branch
- =git branch=  -> mostra todas as branches e em qual você está atualmente
- =git branch <nome>= -> cria uma branch com o nome especificado
- =git branch -m <branch-antiga> <branch-nova>= -> renomeia uma branch local
- =git branch -d <branch>= -> deleta uma branch local
- =git branch -D <branch>= -> deleta uma branch local, descartando todas as mudanças não commitadas
*** git pull <repo-remoto> <branch-destino>
- Faz o download de um repositório remoto para a "branch-destino".
  Irá automaticamente tentar mesclar as duas branches fazendo um "merge"
- =git pull --rebase <repo-remoto> <branh-destino>= -> mesmo que o =git pull=, porém realiza um ~rebase~
*** git diff
- Mostra todas as mudanças realizadas desde o último commit
- =git diff <arquivo>= -> mostra as mudanças de um arquivo desde o último commit
*** git stash
- Salva temporariamente as mudanças não commitadas para serem recuperadas depois, mesmo em outras branches
- =git stash pop= -> recupera as últimas mudanças salvas no stash, na branch atual
*** git merge <branch>
- Mescla a branch especificada com a branch atual
*** git rebase <branch>
- Junta os commits da branch especificada com a atual
*** git cherry-pick <commit-hash>
- Possibilita adicionar um commit de uma branch em outra (nem sempre é a melhor prática)
*** git clean
- Remove arquivos não supervisionados pelo git
- =git clean -f .= -> limpa os arquivos da working tree do diretório atual
- =git clean -fd .= -> limpa os diretórios da working tree
*** git reflog
- Um "diário" que guarda as mudanças na ~HEAD~

** Desfazer erros comuns
*** Descartando mudanças locais e restaurando arquivos
**** git restore <arquivo>
- Descarta todas as mudanças não commitadas de um arquivo até seu último commit
- Se utilizado num arquivo deletado, restaura o arquivo
- =git restore -p <arquivo>= -> oferece a possibilidade de descartar mudanças em partes específicas
- =git restore .= -> descarta todas as mudanças do diretório até o último commit
- =git restore --source <commit-hash>= -> dado um commit hash e um arquivo, isso irá restaurar o arquivo para aquele ponto em
  específico
*** Reverter ou editar um commit
**** git commit --amend -m <mensagem>
- Edita a mensagem de commit do último commit
- Caso tenha esquecido de adicionar uma mudança, adicione ela ao staging e execute o comando
- Esse comando reescreve o histórico de commits (substitui o commit afetado). NÃO UTILIZE CASO JÁ TENHA DADO PUSH NO COMMIT
**** git revert <commit-hash>
- Cria um novo commit o qual possui as mudanças opostas ao commit especificado!
- Para conseguir o commit hash, use =git log=
- Forma segura de "refazer um commit antigo"
**** git reset <commit-hash>
- Retorna para o commit especificado, descartando os commit seguintes
- =git reset --hard <commit-hash>= -> todas as mudanças locais serão descartadas
- =git reset --soft <commit-hash>= -> persiste as mudanças realizadas nos commits

* Github
Github é uma plataforma de hospedagem de código fonte, ou seja, onde criamos repositórios remotos.

** Conceitos iniciais
*** Fork
- "Bifurca" um repositório existe, bem parecido com o =git clone=, porém te permite realizar mudanças e
  criar uma pull request com elas no repositório original
*** Pull Request
- Implementação visual do comando =git pull=, onde o dono do repositório pode rever as mudanças que outra pessoa fez
  no fork dela e decidir se deve ser mesclado ou não em alguma branch. Principal maneira de se fazer code review
  ou contribuir com algum projeto open source
*** Issue
- Abrir uma issue significa abrir uma discussão em um repositório sobre algum assunto. Geralmente é usada
  para descrever bugs de um programa ou sugerir melhorias/mudanças no código fonte
*** Release
- Um dos métodos de distribuição de um projeto. Geralmente é aqui onde os desenvolvedores expõem os binários
  (executáveis) de suas aplicações, junto com um "changelog", indicando as mudanças de cada atualização
*** Gist
- Pequeno trecho de código ou texto
- Seu "nome" geralmente é um hash grande
** Como interagir com o Github
- Existem algumas maneiras de interagir com o Github:
  1. Pelo site oficial -> https://github.com
  2. Pelo aplicativo em GUI oficial -> https://desktop.github.com/
  3. Pela CLI oficial: https://cli.github.com/

Como estamos numa AARE de linha de comando... Vamos de CLI. Porém todas essas ações podem ser replicadas pelo site 😊

*** Instalando a github-cli
No nosso contêiner estamos usando a distro ~Ubuntu~, que é baseada no Debian, logo,
precisamos adicionar o repositório do github e suas chaves para instalar o software:

#+begin_src bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
sudo apt-add-repository https://cli.github.com/packages
sudo apt update
sudo apt install gh
#+end_src

*** Configurando a CLI

Para prosseguir e realizar as listas de exercícios e o teste final, é necessário ter a CLI do github devidamente configurada!
Existem 2 passos para atingir esse objetivo:

1. Adicionar uma chave ~SSH~ na sua conta do Github
2. Se autenticar na CLI

O primeiro passo pode ser executado, seguindo o tutorial para Linux, no site oficial do github:
https://docs.github.com/pt/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Já o segundo passo, pode ser executado com o comando ~gh auth login~, que é descrito na próxima seção.

*** Comandos
**** gh auth
***** gh auth login
- Conecta sua conta do github com o dispositivo atual
***** gh auth logout
- Remove sua conta github do diospositivo atual
**** gh repo
***** gh repo create <nome>
- Cria um repositório remoto no github
  - Caso seja executado dentro de um repositório local (onde foi executado =git init=),
    apenas cria o repo remoto e adiciona uma nova URL como ~origin~
  - Se executado fora de um repositório local, perguntará se deseja criar um no diretório atual
***** gh repo clone <username><repo>
- Igual o =git clone=, porém menos verboso, sem a necessidade de colocar uma URL
***** gh repo fork
- Cria um fork de um repositório no Github
**** gh gist
***** gh gist create <arquivos>
- Cria uma gist com os arquivos especificados
- Retorna o link da gist
***** gh gist delete <gist_id|gist_url>
- Delete a gist especificada
***** gh gist clone <gist> [diretorio]
- Clona uma gist num diretório especificado ou com o nome original
**** gh pr
***** gh pr create
- Cria uma Pull Request no Github da branch que você está para a master/main
***** gh pr merge <pr>
- Dado um número, URL ou nome da branch de uma PR, mescla ela com a branch master/main
***** gh pr diff <pr>
- Dado uma PR, mostra as mudanças propostas por ela
***** gh pr close
- Fecha a Pull Request
***** gh pr comment <pr>
- Dado uma PR, cria um novo comentário

* Referências
- Site oficial Git: https://git-scm.com/
- Fonte dos comandos animados: https://dev.to/lydiahallie/cs-visualized-useful-git-commands-37p1#revert
- Visualize os comandos básicos do git: https://onlywei.github.io/explain-git-with-d3/
- Manual da CLI do Github: https://cli.github.com/manual/
- 18 comandos git: https://towardsdatascience.com/git-commands-cheat-sheet-software-developer-54f6aedc1c46
- Aula completa freeCodeCamp sobre git e github: https://www.youtube.com/watch?v=RGOj5yH7evk&list=PL8Vfm2INuMLE5DMqGlHSYC4wnp0Mna-Vl&index=2
- Aula completa sobre desfazer erros comuns: https://www.youtube.com/watch?v=lX9hsdsAeTk&list=PL8Vfm2INuMLE5DMqGlHSYC4wnp0Mna-Vl&index=3
- Post sobre como usr o =git checkrry-pick=: [[https://gitbetter.substack.com/p/how-to-use-git-cherry-pick-effectively]]
