#+title: Como nunca mais perder aquele arquivo/projeto?
#+author: Matheus de Souza Pessanha
#+email: 00119110328@pq.uenf.br

* Git
~git~ é uma ferramenta de DVCS (Distributed Version Control System), ou "sistema de controle de versões distribuido",
utilizado para versionar (criar versões) diferentes de um arquivo/projeto.

- Criado por Linus Torvalds
- Não é o único VCS, existem outros como: Subversion e Mercurial
- Almeja oferecer a maior flexibilidade, segurança e desempenho
- Relativamente difícil de aprender, pela quantidade de novos conceitos e comandos

** Diferença entre git e Github
- O ~git~ é de fato o software de VCS
- Github é uma plataforma de hospedagem de código fonte, que utiliza o ~git~
  - Outros exemplos, são:
    1. Gitlab
    2. BitBucket

** Instalando o git
- Existe uma versão oficial para windows: https://git-scm.com/download/win
  - Instala em conjunto o "git bash", um emulador de terminal bem limitado com o bash
- Em distros Linux baseadas no Debian, rode: =sudo apt install git=
  - Geralmente o ~git~ já vem instalado por padrão nas distros

** Conceitos inciais
*** Repositório
Bem, nas outras aulas houve uma breve explição do que são repositórios! O ~git~ usa o mesmo conceito.

*** Repositório local
- Lugar onde fica os arquivos na sua máquina, de forma "local"
*** Repositório remoto
- Lugar para onde enviamos as mudanças locais e armazenamos todas as mudanças
- Geralmente usamos uma plataforma, como Github

*** Commit
- Cria um ponto ("save") no seu repositório
- Responsável por criar a "linha do tempo" do projeto

*** Branch
- Imagine seu projeto como uma árvore
- Cria um novo "ramo" do seu projeto!
- Todo projeto possui uma branch raiz padrão ~master~ ou ~main~

*** Staging
- Passo anterior ao ~commit~
- Armazena as mudanças de forma temporária e facilmente reversível

*** Clonar
- É possível clonar repositórios remotos, ou seja, trazer o repositório remoto para um local

*** Push
- Faz o upload dos commits locais para um repositório remoto

*** Pull
- Faz o download das mudanças de um repositório remoto para um local

*** HEAD
- Significa uma referência para o último commit e branch atual
** Comandos
Antes de inciar os comandos, devemos configurar o git localamente, nos identificando:
#+begin_src bash

git config --global user.email "seu@email.com"
git config --global user.name "Seu nome"

#+end_src

- =git init= -> cria um reposit local no diretório atual
- =git clone <repo-remoto> <destino>= -> clona um repositório remoto para sua máquina
  - Existem duas formas de clonar um repositório:
    1. SSH
    2. HTTPS
- =git add <arquivo>= -> adiciona um ou mais arquivos para o staging
  - =git add .= -> adiciona todo o diretório atual para staging
- =git status= -> mostra o estado atual do seu repositório local
- =git log= -> mostra o histórico dos commits
- =git commit -m <mensagem>= -> cria um commit com os arquivos em staging com uma mensagem
- =git push <branch-destino> <branch-font>= -> faz o upload dos commits da "branch-fonte" para um repositório
remoto na "branch-destino"
  - Geralmente chamamos o repositório remoto de "origin"
- =git remote -v= -> mostra todos os repositórios remotos
- =git fetch <repo-remoto>= -> sincroniza o repositório local e repositório remoto
- =git checkout -b <nome-branch>= -> cria uma nova branch com o nome especificado e muda o ~HEAD~ para ela
- =git checkout <branch>= -> muda a ~HEAD~ para uma branch existente
- =git branch=  -> mostra todas as branchs e em qual você está atualmente
  - =git branch -m <branch-antiga> <branch-nova>= -> renomeia uma branch local
  - =git branch -d <branch>= -> delete uma branch local
  - =git push <erpo-remoto> <--delete <branch>= -> deleta uma branch remota
  - =git push <repo-remoto> :<branch-antiga> <nova-branch>= -> renomeia uma branch remota
- =git pull <repo-remoto> <branch-destino>= -> faz o download de um repositório remoto para a "branch-destino".
  Irá automaticamente tentar mesclar as duas branches
- =git diff= -> mostra todas as mudanças realizadas desde o último commit
- =git stash= -> salva temporariamente as mudanças não commitadas para serem recuperadas depois, mesmo em outras branches
  - =git stash pop= -> recupera as últimas mudanças salvas no stash, na branch atual
- =git merge <nome-branch>= -> mescla a branch especificada com a branch atual
- =git cherry-pick <commit-hash>= -> possibilita adicionar um commit de uma branch em outra (nem smepre é a melhor prática)
- =git clean= -> remove arquivos não supervisionados pelo git
  - flag ~-f~ para arquivos
  - flag ~-fd~ para diretórios
- =git reflog= -> um "diário" que guarda as mudanças na do ~HEAD~

** Desfazer erros comuns
- =git restore <arquivo>= -> descarta todas as mudanças não commitadas de um arquivo até seu último commit
  - Se utilizado num arquivo deletado, restaura o arquivo
  - Se utilizado com a flag ~-p~, oferece a possibilidade de descartar mudanças em partes específicas
  - Se utilizado com a entrada ~.~, descarta todas as mudanças do diretório até o último commit
  - Pode ser utilizado com a flag ~--source~, dado um commit hash e um arquivo, isso irá restaurar o arquivo para aquele ponto em
    específico
- =git commit --amend -m <mensagem>= -> edita a mensagem de commit do último commit
  - Caso tenha esquecido de adicionar uma mudança, adicione ela ao staging e execute o comando
  - Esse comando reescreve o histórico de commits (substitui o commit afetado). NÃO UTILIZE CASO JÁ TENHA DADO PUSH NO COMMIT
- =git revert <commit-hash>= -> cria um novo commit o qual possui as mudanças opostas ao commit especificado!
  - Para conseguir o commit hash, use =git log=
  - Forma segura de "refazer um commit antigo"
- =git reset --hard <commit-hash>= -> retorna para o commit especificado, descartando os commit seguintes
  - A flasg ~--hard~ significa que todas as mudanças locais serão descartadas
  - Para persistir as mudanças locais, use =git reset --mixed <commit-hash>=

* Github
Github é uma plataforma de hospedagem de código fonte, ou seja, onde criamos repositórios remotos.

** Conceitos iniciais
*** Fork
- "Bifurca" um repositório existe, bem parecido com o =git clone=, porém te permite realizar mudanças e
  criar uma pull request com elas no repositório original
*** Pull Request
- Implementação visual do comando =git pull=, onde o dono do repositório pode rever as mudanças que outra pessoa fez
  no fork dela e decidir se deve ser mesclado ou não em alguma branch. Principal maneira de se fazer code review
  ou contribuir com algum projeto open source
*** Issue
- Abrir uma issue significa abrir uma discussão em um repositório sobre algum assunto. Geralmente é usada
  para descrever bugs de um programa ou sugerir melhorias/mudanças no código fonte
*** Release
- Um dos métodos de distribuição de um projeto. Geralmente é aqui onde os desenvolvedores expõem os binários
  (executáveis) de suas aplicações, junto com um "changelog", indicando as mudanças de cada atualização
** Como interagir com o Github
- Existem algumas maneiras de interagir com o Github:
  1. Pelo site oficial -> https://github.com
  2. Pelo aplicativo em GUI oficial -> https://desktop.github.com/
  3. Pela CLI oficial: https://cli.github.com/

Como estamos numa AARE de linha de comando... Vamos de CLI. Porém... irei mostrar como fazer as mesmas ações, só que no site 😊

*** Instalando a github-cli
No nosso contêiner estamos usando a distro ~ubuntu~, que é baseada no Debian, logo,
precisamos adicionar o repositório do github e suas chaves para instalar o software:

#+begin_src bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
sudo apt-add-repository https://cli.github.com/packages
sudo apt update
sudo apt install gh
#+end_src

*** Comandos
**** gh auth
***** gh auth login
- Conecta sua conta do github com o dispositivo atual
***** gh auth logout
- Remove sua conta github do diospositivo atual
**** gh repo
***** gh repo create <nome>
- Cria um repositório remoto no github
  - Caso seja executado dentro de um repositório local (onde foi executado =git init=),
    apenas cria o repo remoto e adiciona uma nova URL como ~origin~
  - Se executado fora de um repositório local, perguntará se deseja criar um no diretório atual
***** gh repo clone <username><repo>
- Igual o =git clone=, porém menos verboso, sem a necessidade de colocar uma URL
***** gh repo fork
- Cria um fork de um repositório no Github
**** gh pr
***** gh pr create
- Cria uma Pull Request no Github da branch que você está para a master/main
***** gh pr merge <pr>
- Dado um número, URL ou nome da branch de uma PR, mescla ela com a branch master/main
***** gh pr diff <pr>
- Dado uma PR, mostra as mudanças propostas por ela
***** gh pr close
- Fecha a Pull Request
***** gh pr comment <pr>
- Dado uma PR, cria um novo comentário
* Referências
- Site oficial Git: https://git-scm.com/
- Fonte dos comandos animados: https://dev.to/lydiahallie/cs-visualized-useful-git-commands-37p1#revert
- Visualize os comandos básicos do git: https://onlywei.github.io/explain-git-with-d3/
- Manual da CLI do Github: https://cli.github.com/manual/
- 18 comandos git: https://towardsdatascience.com/git-commands-cheat-sheet-software-developer-54f6aedc1c46
- Aula completa freeCodeCamp sobre git e github: https://www.youtube.com/watch?v=RGOj5yH7evk&list=PL8Vfm2INuMLE5DMqGlHSYC4wnp0Mna-Vl&index=2
- Aula completa spbre desfazer erros comuns: https://www.youtube.com/watch?v=lX9hsdsAeTk&list=PL8Vfm2INuMLE5DMqGlHSYC4wnp0Mna-Vl&index=3
