#Selecionando a imagem base da distro ubuntu ultima versao
FROM ubuntu:latest

#atualizando a lista de pacotes
RUN apt update && apt upgrade -y

#executar o comando echo para imprimir  uma frase
ENTRYPOINT ["echo", "escrevendo..."]
