#Imagem base utilizada na construção da nova imagem
FROM ubuntu:20.10

#Define uma string como parâmetro padrão para o comando do ENTRYPOINT. Ex: echo <string definida no CMD>
CMD ["Passe algum conteúdo para ser exibido. Ex: docker run <nome_da_imagem> Hello!"]

#Define que o container executado a partir dessa imagem será executado como o programa "echo"
ENTRYPOINT ["echo"]
